CREATE TABLE Piece (ID_PIECE INT PRIMARY KEY, nom VARCHAR(255), description VARCHAR(255), prix DECIMAL(10,2));

CREATE TABLE Composition (ID_PIECE_COMPOSEE INT, ID_PIECE_COMPOSANT INT, quantite INT, PRIMARY KEY (ID_PIECE_COMPOSEE, ID_PIECE_COMPOSANT), FOREIGN KEY (ID_PIECE_COMPOSEE) REFERENCES Piece(ID_PIECE), FOREIGN KEY (ID_PIECE_COMPOSANT) REFERENCES Piece(ID_PIECE));
